### ISSUE TITLE
2020/11/04日からexeファイルが起動できなくなった

### ISSUE THREAD

**Issue by Polyotu** [boomxch/StreamingWidget#1]
環境
win10:1909 OSビルド 18363.1139
.NET Core 3.1 Runtimeは3.1.9-win-x86をインストールしました

11/02日の起動を最後に，exeファイルを実行しても一瞬待機状態になるだけとなり起動されなくなりました

試したこと
・再DL(.NET Core 3.1 Runtime含む)
・管理者として実行
・cmdからの実行
・windowsDefenderを停止しての実行
・zipDLして中にあるexeを実行してみる
どれも同様の症状で実行されませんでした．

動いてからエラーという感じではないようで，data/log.txtはdataフォルダごと作成されていませんでした
![image](https://user-images.githubusercontent.com/55525642/98443881-a76df180-2151-11eb-949f-b479137ae243.png)

**Comment by boomxch** [comment]
報告ありがとうございます
こちら、よく報告される問題点なのですが、こちらの自己完結型アプリケーションを使用するとこちらは使用可能であるとの報告もあるため、こちらもお試しください。
[ダウンロードリンク](https://1drv.ms/u/s!Am_cMZT26Ppfgax4zbCiV47P_tWJvA)

**Comment by Polyotu** [comment]
DL後実行したところ，正常に動作しました．ありがとうございます！
![image](https://user-images.githubusercontent.com/55525642/99542048-ef640280-29f4-11eb-9793-919e4f07a873.png)
