### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by shachar700** [boomxch/StreamingWidget#3]
![Screenshot_8](https://user-images.githubusercontent.com/48739719/107363985-8d8ed280-6ae3-11eb-9a79-06ccecb5db93.png)

I tried to login, it didn't work. I hope the streaming widget will be fixed in a future update. :D

🗡️

**Comment by boomxch** [comment]
I made an update for this issue.
Could u try again with new application?
https://github.com/boomxch/StreamingWidget/raw/master/Splatoon2StreamingWidget.exe

**Comment by shachar700** [comment]
It's working now. Thanks :D
