### ISSUE TITLE
No naIdToken key provided

### ISSUE THREAD

**Issue by frozenpandaman** [boomxch/StreamingWidget#4]
Hi,

I'm the developer of [splatnet2statink](https://github.com/frozenpandaman/splatnet2statink) & the s2s API. I'm seeing a number of these entries in the API log recently:
```
"122.xxx.xxx.xxx", "2021-02-17 07:59:15", "Splatoon2StreamingWidget/1.2.5", 400, "No naIdToken key provided"
[...]
"2404:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx", "2021-02-27 23:40:22", "Splatoon2StreamingWidget/1.2.6", 400, "No naIdToken key provided"
[...]
"115.xxx.xxx.xxx", "2021-03-12 13:19:08", "Splatoon2StreamingWidget/1.2.6", 400, "No naIdToken key provided"
```

Could you make sure the request is getting sent [properly](https://github.com/frozenpandaman/splatnet2statink/wiki/api-docs#splatnet2statink-api-documentation) (with `naIdToken` provided in the body) every time, if possible? Thanks!

**Comment by boomxch** [comment]
Sorry, thank you for posting the issue.
From ver1.2.7, it's changed to check if the content to be sent is empty before sending it.
(It may be that the naID was sent empty a couple of times in the communication sent for debugging in ver1.2.7.)

**Comment by frozenpandaman** [comment]
Cool, thank you so much, and great project! :)
