### ISSUE TITLE
2021/08/17からエラーが起こるようになった

### ISSUE THREAD

**Issue by Polyotu** [boomxch/StreamingWidget#6]
タイトル通り，起動してurlを初回起動時の手順で入力してもXP表示前の画面で固まるようになってしまいました
exeファイルを消して更新，.NET 5.0 Runtimeが入っているかも確認，単独動作版も試しましたが動作しないので
log.txtを確認したところ．失敗しているのだけはなんとなくわかりました

先頭のログが02/22なのはバックアップをいじったからで，08/16時点では戦績取得できていました
[log.txt](https://github.com/boomxch/StreamingWidget/files/7000330/log.txt)

**Comment by boomxch** [comment]
issueありがとうございます
今回使用したアプリケーションは最新版(ver1.2.10)でしょうか？

**Comment by Polyotu** [comment]
いえ，1.2,9です
1.2.10をDLして試してみます

**Comment by Polyotu** [comment]
![image](https://user-images.githubusercontent.com/55525642/129746442-1fc6d636-fd55-4c65-8a50-3685d366d18e.png)
1.2.10では無事動作しました，ありがとうございます！

**Comment by boomxch** [comment]
了解しました!
解決してよかったです☺️
ご報告ありがとうございました🙇
